import { describe, expect, it } from 'vitest'
import fs from 'node:fs'
import path from 'node:path'

describe('App source', () => {
  it('renders fixed desktop shell with theme switch, notice layer and retained drafts after submit', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const preloadSource = fs.readFileSync(path.resolve(process.cwd(), 'main/preload.js'), 'utf8')

    expect(source).toContain('AppTopBar')
    expect(source).toContain('ActivationGate')
    expect(source).toContain('WorkspaceSidebar')
    expect(source).toContain('DesignWorkspace')
    expect(source).toContain('TaskManagerSidebar')
    expect(source).toContain('shell-grid')
    expect(source).toContain('秋 Ai')
    expect(source).toContain('暗黑')
    expect(source).not.toContain('明亮')
    expect(source).not.toContain('护眼')
    expect(source).toContain('getStudioSnapshot')
    expect(source).toContain('getActivationStatus')
    expect(source).toContain('importLicenseFile')
    expect(source).toContain('saveSettings')
    expect(source).toContain('showActionFeedback')
    expect(source).toContain('buildErrorMessage')
    expect(source).toContain('app-notice-layer')
    expect(source).toContain('成功')
    expect(source).toContain('失败')
    expect(source).toContain('handleClearRuntimeState')
    expect(source).toContain('@cleanup-click="handleClearRuntimeState"')
    expect(source).toContain('scheduleDraftPersist')
    expect(source).toContain('hasActiveStudioTasks')
    expect(source).toContain('activationState')
    expect(source).toContain('isActivated')
    expect(source).toContain('handleImportLicense')
    expect(source).toContain('handleCopyDeviceCode')
    expect(source).toContain('resetDraftForMenu')
    expect(source).not.toContain('await resetActiveDraftAfterSubmit()')
    expect(source).toContain('可能导致保留原图或生成失败')
    expect(source).toContain('AdminPasswordDialog')
    expect(source).toContain('AdminApiKeyDialog')
    expect(source).toContain('adminLogoClickCount')
    expect(source).toContain('isAdminPasswordDialogVisible')
    expect(source).toContain('isAdminApiConfigUnlocked')
    expect(source).toContain('isAdminApiKeyDialogVisible')
    expect(source).toContain('adminPasswordDraft')
    expect(source).toContain('adminApiKeyDraft')
    expect(source).toContain('handleConfirmAdminPassword')
    expect(source).toContain('saveAdminApiKey')
    expect(source).toContain('listNegativePromptTemplates')
    expect(source).toContain('saveNegativePromptTemplate')
    expect(source).toContain('removeNegativePromptTemplate')
    expect(source).toContain('negativePromptTemplates')
    expect(source).toContain('fixedNegativePromptTemplates')
    expect(source).toContain('customNegativePromptTemplates')
    expect(source).toContain('loadNegativePromptTemplateState')
    expect(source).toContain('applyNegativeTemplateSelection')
    expect(source).toContain("field === 'negativeTemplateId'")
    expect(source).toContain("negativePrompt: matchedTemplate?.prompt || ''")
    expect(source).toContain('管理员验证失败：密码错误')
    expect(source).toContain("message: '管理员验证通过，请继续保存 API-Key'")
    expect(source).toContain("message: 'API-Key 已保存成功'")
    expect(source).toContain('isAdminApiConfigUnlocked.value = false')
    expect(source).toContain('adminApiKeyDraft.value = settings.apiKey || \'\'')
    expect(source).toContain('if (adminLogoClickCount.value >= 5)')
    expect(source).not.toContain('@wechat-click=')
    expect(source).not.toContain('handleWechatClick')
    expect(preloadSource).toContain('PROMPT_TAGS_LIST')
    expect(preloadSource).toContain('PROMPT_TAGS_SAVE_CATEGORY')
    expect(preloadSource).toContain('PROMPT_TAGS_SAVE_TAG')
    expect(preloadSource).toContain('PROMPT_TAGS_REMOVE_TAG')
    expect(preloadSource).toContain('PROMPT_TAGS_REMOVE_CATEGORY')
    expect(source).toContain("promptTagMap.value.get(tagId)?.name || ''")
    expect(source).not.toContain("promptTagMap.value.get(tagId)?.prompt || ''")
  })

  it('uses prompt library sidebar item together with studio menus without copywriting', () => {
    const sidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/WorkspaceSidebar.vue'), 'utf8')
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(sidebarSource).toContain('工作台')
    expect(sidebarSource).toContain('单图测试')
    expect(sidebarSource).toContain('单图设计')
    expect(sidebarSource).toContain('套图设计')
    expect(sidebarSource).toContain('套图生成')
    expect(sidebarSource).toContain('模型价格')
    expect(sidebarSource).toContain('提示词库')
    expect(sidebarSource).not.toContain('文案设计')
    expect(sidebarSource).toContain("key: 'workspace'")
    expect(sidebarSource).toContain("key: 'single-image'")
    expect(sidebarSource).toContain("key: 'single-design'")
    expect(sidebarSource).toContain("key: 'series-design'")
    expect(sidebarSource).toContain("key: 'series-generate'")
    expect(sidebarSource).toContain("key: 'model-pricing'")
    expect(sidebarSource).toContain("key: 'prompt-library'")
    expect(sidebarSource).not.toContain("key: 'copywriting'")
    expect(appSource).not.toContain("{ key: 'copywriting', label: '文案设计' }")
    expect(appSource).toContain("{ key: 'prompt-library', label: '提示词库' }")
    expect(sidebarSource).toContain('菜单点击事件预留')
  })

  it('renders task sidebar with workspace queue and design export modes only', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(source).toContain('任务队列')
    expect(source).toContain('单图测试')
    expect(source).toContain('单图设计')
    expect(source).toContain('套图设计')
    expect(source).toContain('套图生成')
    expect(source).not.toContain('文案设计')
    expect(source).toContain('等待中')
    expect(source).toContain('进行中')
    expect(source).toContain('已完成')
    expect(source).toContain('失败')
    expect(source).toContain('生成时间')
    expect(source).toContain('formatTaskNumber')
    expect(source).toContain('10 个任务')
    expect(source).toContain('pagination-arrow-button')
    expect(source).toContain('pagination-arrow-button__triangle--left')
    expect(source).toContain('pagination-arrow-button__triangle--right')
    expect(source).toContain('aria-label="上一页"')
    expect(source).toContain('aria-label="下一页"')
    expect(source).toContain('currentPage')
    expect(source).toContain('结束任务')
    expect(source).toContain('stop-task')
    expect(source).toContain('isStoppableTask')
    expect(source).toContain('ResultExportPanel')
    expect(source).toContain('showWorkspaceTasks')
    expect(source).toContain('showExportPanel')
    expect(source).toContain('downloadCleanupEnabled')
    expect(source).toContain('toggle-download-cleanup')
    expect(source).not.toContain("props.activeMenu === 'prompt-library'")
    expect(source).not.toContain("props.activeMenu === 'copywriting'")
    expect(source).toContain('当前页面暂无侧边内容')
  })

  it('renders dashboard workspace, prompt library, single-block model pricing, and focus display design pages', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(source).toContain('WorkspaceDashboard')
    expect(source).toContain("activeMenu === 'workspace'")
    expect(source).toContain('PromptLibraryPanel')
    expect(source).toContain("activeMenu === 'prompt-library'")
    expect(source).toContain('ParameterSettingsPanel')
    expect(source).toContain('ResultDisplayPanel')
    expect(source).not.toContain('ResultExportPanel')
    expect(source).toContain("activeMenu === 'model-pricing'")
    expect(source).toContain('workspace-panels--single')
    expect(source).toContain('workspace-panels--focus-display')
    expect(source).toContain('single-design')
    expect(source).toContain('latestTask')
    expect(source).toContain(':prompt-templates="allPromptTemplates"')
    expect(source).toContain(':custom-prompt-templates="customPromptTemplates"')
    expect(source).toContain(':fixed-negative-prompt-templates="fixedNegativePromptTemplates"')
    expect(source).toContain(':custom-negative-prompt-templates="customNegativePromptTemplates"')
    expect(source).not.toContain('@update-api-key=')
    expect(source).not.toContain('@switch-api-key=')
    expect(source).not.toContain('@save-api-config=')
    expect(source).not.toContain('select-copywriting-images')
    expect(source).not.toContain('clear-copywriting-images')
  })

  it('defines image-generation model pools and omits copywriting-specific options', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).not.toContain('const copywritingModelOptions = [')
    expect(source).toContain('const imageModelOptions = [')
    expect(source).toContain('nano-banana-fast')
    expect(source).toContain('nano-banana-pro-4k-vip')
    expect(source).toContain('const currentModelOptions = computed(() => {')
    expect(source).not.toContain("if (activeMenu.value === 'copywriting')")
    expect(source).toContain('currentModelOptions')
    expect(source).toContain('const allPromptTemplates = computed(() => {')
    expect(source).toContain('Math.min(100')
    expect(source).toContain('currentLongRunningHint')
    expect(source).toContain('当前任务量很大，将进入长队列执行。')
    expect(source).toContain('当前任务量较大，生成时间会明显变长。')
  })

  it('defines a recharge catalog for the model pricing page', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const rechargePricingCatalog = [')
    expect(source).toContain("price: '30¥'")
    expect(source).toContain("credits: '100000积分'")
    expect(source).toContain("bonus: '送25%'")
    expect(source).toContain("price: '3000¥'")
    expect(source).toContain("credits: '20000000积分'")
    expect(source).toContain(':recharge-pricing-catalog="rechargePricingCatalog"')
  })

  it('keeps only needed pricing models and orders them by ascending credits', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).not.toContain("name: 'gemini-3-pro'")
    expect(source).not.toContain("name: 'gemini-3.1-pro'")
    expect(source).not.toContain("name: 'gemini-2.5-pro'")
    expect(source).not.toContain("name: 'sora-create-character'")
    expect(source).not.toContain("name: 'sora-upload-character'")

    expect(source.indexOf("name: 'nano-banana-fast'")).toBeLessThan(source.indexOf("name: 'gpt-image-2'"))
    expect(source.indexOf("name: 'gpt-image-2'")).toBeLessThan(source.indexOf("name: 'nano-banana-2'"))
    expect(source.indexOf("name: 'nano-banana-2'")).toBeLessThan(source.indexOf("name: 'nano-banana'"))
    expect(source.indexOf("name: 'nano-banana'")).toBeLessThan(source.indexOf("name: 'nano-banana-2-cl'"))
    expect(source.indexOf("name: 'nano-banana-2-cl'")).toBeLessThan(source.indexOf("name: 'nano-banana-pro'"))
  })

  it('wires image upload actions through the workspace shell', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const workspaceSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/DesignWorkspace.vue'), 'utf8')

    expect(appSource).toContain('pickStudioInputAssets')
    expect(appSource).toContain('uploadDirectoryDrafts')
    expect(appSource).toContain('handleUploadDirectoryDraftUpdate')
    expect(appSource).toContain('handleSaveUploadDirectory')
    expect(appSource).toContain('handleOpenSingleImagePicker')
    expect(appSource).toContain('handleOpenSingleImagePicker')
    expect(workspaceSource).toContain('select-single-design-image')
    expect(appSource).toContain('handleOpenSingleDesignImagePicker')
    expect(appSource).toContain('handleOpenSeriesDesignPicker')
    expect(appSource).toContain('handleOpenSeriesGeneratePicker')
    expect(appSource).toContain('saveSettings({')
    expect(appSource).toContain('uploadDirectories:')
    expect(appSource).toContain("preview: preview")
    expect(appSource).toContain("typeof file.preview === 'string' ? file.preview : ''")
    expect(appSource).not.toContain('globalUploadDirectory')
    expect(workspaceSource).toContain('save-upload-directory')
    expect(workspaceSource).toContain('update-upload-directory-draft')
    expect(appSource).not.toContain('handleSelectCopywritingImages')
    expect(appSource).not.toContain('handleClearCopywritingImages')
    expect(workspaceSource).not.toContain('select-copywriting-images')
    expect(workspaceSource).not.toContain('clear-copywriting-images')
    expect(appSource).not.toContain('copyMode')
    expect(appSource).not.toContain('referenceImages')
    expect(appSource).not.toContain('copywritingImageInput')
    expect(appSource).not.toContain('return encodeURI(`file:///')
  })

  it('wires export panel output-directory action through the desktop bridge', () => {
    const appSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')
    const taskSidebarSource = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/components/TaskManagerSidebar.vue'), 'utf8')

    expect(taskSidebarSource).toContain('open-output-directory')
    expect(taskSidebarSource).toContain('exportItems')
    expect(taskSidebarSource).toContain('selectedExportIds')
    expect(taskSidebarSource).toContain('stop-task')
    expect(appSource).toContain('handleOpenOutputDirectory')
    expect(appSource).toContain('handleStopTask')
    expect(appSource).toContain('stopStudioTask')
    expect(appSource).toContain('openOutputDirectory')
    expect(appSource).toContain('latestTaskForActiveMenu')
  })

  it('only shows latest task progress for the active menu instead of falling back to other modules', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('const matchedTask = sortedTasks.value.find((task) => task.menuKey === activeMenu.value)')
    expect(source).toContain('return matchedTask || null')
    expect(source).not.toContain('return matchedTask || sortedTasks.value[0] || null')
  })

  it('optimistically updates queued task state after submit instead of waiting on a full snapshot refresh', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('function upsertTaskIntoState(task)')
    expect(source).toContain('const createdTask = await createStudioTask({')
    expect(source).toContain('upsertTaskIntoState(createdTask)')
    expect(source).not.toContain('await resetActiveDraftAfterSubmit()')
    expect(source).toContain('buildDraftForSubmit')
    expect(source).toContain('detectPromptRisk')
    expect(source).toContain('void refreshStudioRuntimeState()')
    expect(source).toContain('creditAdjustmentAmount')
    expect(source).toContain('totalCreditAmount')
    expect(source).toContain('handleApplyCreditAdjustment')
    expect(source).toContain('handleTotalCreditValueUpdate')
    expect(source).toContain('handleSaveTotalCredits')
    expect(source).toContain("creditAdjustment: {")
    expect(source).toContain('creditState: {')
    expect(source).toContain('totalPurchasedCredits: normalizedTotalCredits')
    expect(source).not.toContain('handleSaveApiConfig')
    expect(source).not.toContain('handleApiKeyUpdate')
    expect(source).not.toContain('handleSwitchApiKey')
  })

  it('persists the export auto-cleanup preference and deletes selected folders after successful download', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('downloadCleanupEnabled')
    expect(source).toContain('handleToggleDownloadCleanup')
    expect(source).toContain('downloadCleanupEnabled: value')
    expect(source).toContain('const exportedIds = [...selectedExportIds.value]')
    expect(source).toContain('if (downloadCleanupEnabled.value)')
    expect(source).toContain('Promise.allSettled(exportedIds.map((exportItemId) => deleteStudioExportItem({')
    expect(source).toContain('批量下载成功，已自动清理已导出的结果文件夹')
    expect(source).toContain('批量下载成功，但部分结果文件夹自动清理失败')
  })

  it('defaults export folders to checked state whenever export items refresh', () => {
    const source = fs.readFileSync(path.resolve(process.cwd(), 'renderer/src/App.vue'), 'utf8')

    expect(source).toContain('function resolveSelectedExportIdsForMenu(menuKey)')
    expect(source).toContain('selectedExportIds.value = resolveSelectedExportIdsForMenu(activeMenu.value)')
    expect(source).toContain('selectedExportIds.value = resolveSelectedExportIdsForMenu(menuKey)')
  })
})
